In [43]:
print("Hello")

Hello


In [44]:
a = 1

In [45]:
a

1

In [46]:
b = [1,2,3,4,5]

In [47]:
b

[1, 2, 3, 4, 5]

In [48]:
b*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [49]:
import numpy as np
x = np.array([3,1,2,'1'])
print(x)
print(type(x))
print(type([3,1,2]))

['3' '1' '2' '1']
<class 'numpy.ndarray'>
<class 'list'>


In [50]:
c = [[1],[1,2]]
d = np.array([[1,1],[1,2]])

for x,y in d:
    print(x,y)


1 1
1 2


In [51]:
%ls

 C ����̺��� �������� �̸��� �����ϴ�.
 ���� �Ϸ� ��ȣ: 3E99-60B8

 c:\Users\minch\TT ���͸�

2024-12-13  ���� 11:45    <DIR>          .
2024-12-13  ���� 12:14    <DIR>          ..
2024-12-10  ���� 11:21    <DIR>          __pycache__
2024-12-13  ���� 12:12             3,459 1.ipynb
2024-12-08  ���� 03:21             1,083 1.py
2024-12-09  ���� 09:02             2,758 10.py
2024-12-07  ���� 09:15             1,917 11.py
2024-12-09  ���� 09:49             4,946 12.py
2024-12-11  ���� 08:03             5,800 13.py
2024-12-11  ���� 06:56             5,303 14.py
2024-12-11  ���� 07:33             1,706 15.py
2024-12-13  ���� 09:42             4,389 16.py
2024-12-13  ���� 10:53             2,234 17.py
2024-12-06  ���� 08:57             3,224 2.py
2024-12-05  ���� 09:08             1,095 3.py
2024-12-01  ���� 04:33             1,499 4.py
2024-12-02  ���� 07:00             1,082 5.py
2024-12-06  ���� 08:57             4,018 6.py
2024-12-06  ���� 08:57             3,838 7.py
2024-12-06  ���� 08:57   

In [52]:
x = np.array([1.0,2.0,3.0])
y = np.array([2.0,4.0,6.0])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [56]:
print(x.shape)
print(x.dtype)
print(d.shape)
print(y/2.0)

(3,)
float64
(2, 2)
[1. 2. 3.]


In [74]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.ndim)

2


In [76]:
print(a.shape)

(3, 2)


In [80]:
a = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
print(a.ndim)
print(a.shape)

3
(3, 2, 1)


In [82]:
np.dot(4,2)

8

In [84]:
ndar1 = np.array([3,2])
ndar2 = np.array([4,6])
np.dot(ndar1,ndar2)

24

In [85]:
ndar1 = np.array([[1,2],[3,4]])
ndar2 = np.array([[1,2],[3,4]])
np.dot(ndar1,ndar2)

array([[ 7, 10],
       [15, 22]])

In [87]:
# ndar1 = np.array([[1],[3]])
# ndar2 = np.array([[1,2],[3,4]])
# np.matmul(ndar1,ndar2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [89]:
ndar2 = np.array([[1,2],[3,4]])
print(ndar2.shape)
print(ndar2.ndim)
a = ndar2.flatten()
print(a.shape)

(2, 2)
2
(4,)


In [90]:
ndar2 = np.array([[[1],[2]],[[3],[4]]])
print(ndar2.shape)
print(ndar2.ndim)
a = ndar2.flatten()
print(a.ndim)
print(ndar2)

(2, 2, 1)
3
1
[[[1]
  [2]]

 [[3]
  [4]]]


In [92]:
ndarr = np.array([[1,2],[2,3],[3,4]])
ndarr.reshape(2,3)

array([[1, 2, 2],
       [3, 3, 4]])

In [95]:
ndarr = np.array([[1,2],[2,3],[3,4]])
ndarr.reshape(6,1)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [4]])

In [96]:
np.random.randint(5,size=(2,4))

array([[1, 1, 1, 1],
       [0, 4, 4, 4]])

In [97]:
np.random.rand(2,4)

array([[7.80968260e-04, 5.41507748e-01, 5.03278659e-01, 4.23496175e-01],
       [5.08519280e-01, 9.06199456e-01, 1.01594901e-01, 3.61886323e-01]])

In [98]:
rng = np.random.default_rng()

In [99]:
rng.random()

0.8506222480480645

In [100]:
rng.integers(0,10,(2,4))

array([[9, 6, 3, 6],
       [6, 2, 1, 6]], dtype=int64)

In [101]:
ndarr = np.array([[6,3],[5,2],[4,1]])
ndarr > 4

array([[ True, False],
       [ True, False],
       [False, False]])

In [105]:
ndarr[ndarr > 1]

array([6, 3, 5, 2, 4])

In [107]:
ndarr[[[ True, True],
       [ True, True],
       [True, False]]]

array([6, 3, 5, 2, 4])