In [ ]:
# 실습. numpy 모듈 사용해보기1
# 1. 10개의 0으로 채워진 array를 만들고 출력해보세요.
# 2. 1번에서 만들어진 array에서 5번쨰 값을 1로 바꾸고 출력해주세요.
# 3. 10부터 30까지의 수로 이뤄진 array를 만들고 출력해주세요.
# 4. 0부터 99까지의 난수로 이루어진 2x2 array를 만들고 출력해주세요.
# 0부터 1사이의 난수로 이루어진 2x4 array를 만들고 출력해주세요.

In [29]:
import numpy  #1
x = numpy.zeros(10)
print(x)

x[4] = 1#2
print(x)

print(numpy.arange(10,31))  #3

print(numpy.random.randint(0,99,size=(2,2)))  #4

print(numpy.random.rand(2,4))  #5 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[[49 37]
 [57 72]]
[[0.73107372 0.1366699  0.43318445 0.58435961]
 [0.65517799 0.30448094 0.65203168 0.15498775]]


In [5]:
# 실습. numpy 모듈 사용해보기2
# 6. 35 ~ 74 까지의 순차적인 수로 이뤄진 1차원 배열을 만들고 10x4 행렬로 변환후 출력
# 7. 6에서 만든 배열을 맨 끝의 행부터 역순으로 출력
# 8. 6에서 만들 배열 중 두 번쨰 행부터 마지막 직전 행까지, 세번쨰 열부터 마지막 열까지 슬라이싱 해서 출력
# 9. 6에서 만든 배열에서 마지막 열에 해당하는 모든 값을 출력(1차원 배열로)
#     #9-1 6번에서 만든 배열에서 마지막 열에 해당하는 모든 값을 출력(2차원 배열로)
# 10. 9-1에서 만든 배열을 역순으로 정렬 후 출력
# 11. 1 ~ 50까지 난수로 된 5x6 배열을 만들고, 배열에서 짝수만 선택해 출력하는 코드 작성

[0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0]


In [151]:
# 6. 35 ~ 74 까지의 순차적인 수로 이뤄진 1차원 배열을 만들고 10x4 행렬로 변환후 출력
import numpy as np
a = np.arange(35,75)
b =a.reshape(10,4)
print(b)


[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]


In [147]:
# 7. 6에서 만든 배열을 맨 끝의 행부터 역순으로 출력
c = b[::-1]
print(c)

[[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]


In [150]:
# 8. 6에서 만들 배열 중 두 번쨰 행부터 마지막 직전 행까지, 세번쨰 열부터 마지막 열까지 슬라이싱 해서 출력
print(c[1:-1,2:])

[[69 70]
 [65 66]
 [61 62]
 [57 58]
 [53 54]
 [49 50]
 [45 46]
 [41 42]]


In [160]:
# 9. 6에서 만든 배열에서 마지막 열에 해당하는 모든 값을 출력(1차원 배열로)
     #9-1 6번에서 만든 배열에서 마지막 열에 해당하는 모든 값을 출력(2차원 배열로)

d = b[-1:].flatten()
print(d)

e = d.reshape(2,2)
print(e)

[71 72 73 74]
[[71 72]
 [73 74]]


In [173]:
# 10. 9-1에서 만든 배열을 역순으로 정렬 후 출력
f = e[::-1]
print(f)

[[73 74]
 [71 72]]


In [179]:
#11. 1 ~ 50까지 난수로 된 5x6 배열을 만들고, 배열에서 짝수만 선택해 출력하는 코드 작성
g = np.random.randint(1,51,size=(5,6))
print(g)
print(g[g/2 == 0])

[[42 27 49 19 21 11]
 [ 2 44  4 42 32 36]
 [24 25 12 37 34 48]
 [29 48 37 41 43 44]
 [26 36 41 24 42 23]]
[]
