In [4]:
import numpy as np
# a = np.array([[1,2],[3,4]])
# expanded = np.expand_dims(a,0)
# print(expanded)
# print(expanded.shape)

[[[1 2]
  [3 4]]]
(1, 2, 2)


In [8]:
# a = [1,2,2,3,3,4,4]
# u_a,indexs = np.unique(a,return_counts=True)
# print(u_a)
# print(indexs)

[1 2 3 4]
[1 2 2 2]


In [18]:
# a = [1,2,2,3,4,3,4,3,1]
# u_a,indexs,counts = np.unique(a,return_index=True,return_counts=True)
# print(u_a)
# print(indexs)
# print(counts)

[1 2 3 4]
[0 1 3 4]
[2 2 3 2]


In [25]:
# a = [1,2,2,3,4,3,4,3,1]
# u_a,counts,indexs = np.unique(a,return_counts=True,return_index=True)
# print(u_a)
# print(indexs)
# print(counts)

[1 2 3 4]
[2 2 3 2]
[0 1 3 4]


In [26]:
# def add(a=1, b=1):
#     return a,b,a+b  # 리턴한 순서대로 print(출력) 결과가 나온다.

# a,b,sum = add(2,3)
# print(a,b,sum)

2 3 5


In [49]:
import numpy as np
a = np.array([1,4,2,3])
b = np.sort(a)  # a[np.argsort(a)]와 동일
print(f'a {a}')
print(f'b {b}')
c = np.argsort(a) # sort 했을떄 다시 돌아갈 주소를 찾는 느낌.?
print(f"c {c}")
print(f'cc {a[c]}')
a[c.sort()]

a [1 4 2 3]
b [1 2 3 4]
c [0 2 3 1]
cc [1 2 3 4]


array([[1, 4, 2, 3]])

In [50]:
x = np.array([1,4,2,3,])
np.mean(x)
np.std(x)
np.var(x)
np.max
np.min


<function min at 0x000001C4251CFF30>

In [44]:
# 실습 numpy 모듈 사용해보기2
# [1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100]
# * 위와 같은 데이터가 있을떄
# 1. 중복을 제거한 배열 출력
# 2. 1의 결과의 최대 , 최소, 평균값 출력
# 3. 1의 결과의 모든 합 출력
# 4. 중복을 제거하지 않은 배열의 중간값 출력.


In [53]:
a = [1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100]
# 1. 중복을 제거한 배열 출력
import numpy as np
import math
a1 = np.unique(a)
print(a1)

[  1   2   3   4   5   7   8   9  10  11  24 100]


In [56]:
# 2. 1의 결과의 최대 , 최소, 평균값 출력
#최대
a21 = a1.max()
print(a21)
a22= a1.min()
print(a22)
a23 = a1.mean()
print(a23)

100
1
15.333333333333334


In [62]:
# 3. 1의 결과의 모든 합 출력
a3 = np.sum(a1)
print(a3)

184


In [64]:
import numpy as np
# 4. 중복을 제거하지 않은 배열의 중간값 출력.
a4 = np.median(a)
print(a4)

5.0


In [113]:
# 실습 Numpy 모듈 사용해보기3
x = np.arange(15,dtype = np.int64).reshape(3,5)
x[1:,::2] = -99
print(x)
# * 위와 같은 데이터가 있을 때
# 1. 1열의 최대, 최소, 평균값 출력
# 2. 2행의 모든 합 출력
# 3. 실습 2번 1차원 배열을 argsort 이용하여 내림차순 정렬.

[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]


In [74]:
# 1. 1열의 최대, 최소, 평균값 출력
x11 = x.max(axis=1)
print(x11)
x12 = x.min(axis=1)
print(x12)
x13 = x.mean(axis=1)
print(x13)

[ 4  8 13]
[  0 -99 -99]
[  2.  -56.6 -54.6]


In [124]:
# 2. 2행의 모든 합 출력
x2 = x[1]
print(sum(x2))

-283


In [111]:
# 3. 실습 2번 1차원 배열을 argsort 이용하여 내림차순 정렬.
a = [1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100]
x3 =np.argsort(a)
print(x3)
x31 = np.array(a) # 원본값을 정렬한 것에 argsort한 값을 넣으니 기존 값이 반환된다.
x32 = x31[x3]  # array를 한 것에 꼭 값을 넣어야한다. 
print(x32[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[100  24  11  10   9   8   7   5   5   5   5   4   3   2   1   1]
